#pr:
#  - features/*
#  - develop/*
#
#trigger:
#  - main

variables:
  - name: 'Main.Branch'
    value: refs/heads/main

jobs:
  - job: "build"
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        displayName: Install LinkedWay-UI
        inputs:
          command: custom
          verbose: true
          customCommand: install

      - task: Npm@1
        displayName: Run Lint
        inputs:
          command: custom
          verbose: true
          customCommand: run-script lint

      - task: Npm@1
        displayName: Run tests
        inputs:
          command: custom
          verbose: true
          customCommand: run-script test

      - task: Npm@1
        displayName: Run build
        inputs:
          command: custom
          verbose: true
          customCommand: run-script build --prod
        condition: eq(variables['Build.SourceBranch'], variables['Main.Branch'])

      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: LinkedWay
        condition: eq(variables['Build.SourceBranch'], variables['Main.Branch'])

      - task: Docker@2
        displayName: Build and Push ($(Main.Branch))
        inputs:
          command: buildAndPush
          repository: lw-ui
          tags: |
            0.0-$(Build.BuildNumber).0
            latest
        condition: eq(variables['Build.SourceBranch'], variables['Main.Branch'])
